import {
  Spacing1,
  Spacing2,
  Spacing3,
  Spacing4,
  Spacing5,
  Spacing6,
  Spacing7,
  Spacing8,
  Spacing9,
  Spacing10,
  Spacing12,
  Spacing14,
  Spacing16,
  Spacing20,
  Spacing24,
  Spacing28,
  Spacing32,
  SpacingPx,
} from '../build/js'

export const space = {
  px: `${SpacingPx.top}px`,
  1: `${Spacing1.top}px`,
  2: `${Spacing2.top}px`,
  3: `${Spacing3.top}px`,
  4: `${Spacing4.top}px`,
  5: `${Spacing5.top}px`,
  6: `${Spacing6.top}px`,
  7: `${Spacing7.top}px`,
  8: `${Spacing8.top}px`,
  9: `${Spacing9.top}px`,
  10: `${Spacing10.top}px`,
  12: `${Spacing12.top}px`,
  14: `${Spacing14.top}px`,
  16: `${Spacing16.top}px`,
  20: `${Spacing20.top}px`,
  24: `${Spacing24.top}px`,
  28: `${Spacing28.top}px`,
  32: `${Spacing32.top}px`,
} as const
